export class ProposalModel {
  editProposal: object;
}

// "proposalId": "948393",
//   "id": 257645,
//   "statusCode": 200,
//   "result": {
//     "_sourceObject": {
//       "proposalEntity": {
//         "enrollmentId": null,
//         "id": 257645,
//         "proposalId": "948393",
//         "customerName": null,
//         "createdByAlias": "V2Alias",
//         "createdDate": "2021-06-21T11:00:15.8118198Z",
//         "status": 0,
//         "delegatingPartyAlias": null,
//         "delegationStatus": 0,
//         "version": "AAAAAAAgJA0=",
//         "isConsolidated": null,
//         "isNonPricingConsolidated": null,
//         "delegatedTo": null,
//         "lastModified": "2021-06-21T11:00:15.8119304Z",
//         "currentOwner": null,
//         "notes": null,
//         "delegationRequestedByAlias": null,
//         "clonedFromProposalId": null,
//         "supressHeadersFooters": null,
//         "isInActive": null,
//         "pricingCountry": "Australia",
//         "lastModifiedBy": "V2Alias",
//         "ctmFooterID": null,
//         "isShared": null,
//         "isSubmitted": false,
//         "highestEmpowerment": null,
//         "isArchive": false,
//         "ctmCode": null,
//         "isPricing": false,
//         "pageBreak": null,
//         "agreementId": null,
//         "identifier": null,
//         "dealNickname": null,
//         "hrddTotalValue": null,
//         "hrddMaxDiscount": null,
//         "isLinked": false,
//         "isMasterProposal": false,
//         "linkedProposalId": null,
//         "isDraft": false,
//         "isDeleted": false,
//         "proposalSharings": [],
//         "proposalAmendments": [],
//         "proposalValidationResults": []
//       },
//       "amendmentIds": null,
//       "delegatingParty": null,
//       "delegationStatus": 0,
//       "delegatedTo": null,
//       "notes": null,
//       "isFromDateRangeDelegation": false,
//       "amendments": [
//         {
//           "pId": 257645,
//           "id": 343291,
//           "code": "M42",
//           "ctmAmendmentCode": null,
//           "language": "JPN",
//           "empowerment": "Business Desk",
//           "documentId": 17446,
//           "isCTM": false,
//           "stream": null,
//           "fileName": "(M42)EnrAmend(MixCALs)(WW)(JPN)(Jul2011)v2(IU).docx",
//           "ctmFooterCode": null,
//           "blobStoragePath": null,
//           "order": 1,
//           "fileVersion": null,
//           "loc": null,
//           "di": null,
//           "isEdited": false,
//           "isConsolidated": false,
//           "type": 0,
//           "ctmCode": null,
//           "link": null,
//           "isPricingAmendment": false,
//           "isCTMPricing": false,
//           "footerCode": null,
//           "isEditField": false,
//           "isCTMAmendment": false,
//           "hasEditableTable": false,
//           "discount": null,
//           "dealSize": null,
//           "beginDate": null,
//           "endDate": null,
//           "commitToConsume": null,
//           "currencyCode": null,
//           "ctmFooterId": null
//         }
//       ],
//       "consolidation": null,
//       "metaData": {
//         "id": 0,
//         "customerName": null,
//         "pricingCountry": null,
//         "lcAlias": null,
//         "operationCenterId": 0,
//         "programId": 0,
//         "notes": null,
//         "proposalId": 0,
//         "nonPricingFileName": null,
//         "pricingFileName": null
//       }
//     },
//     "_errorMsg": null,
//     "_statusCode": 200
//   }
